version: 2
jobs:
  Unit Test:
    docker:
      - image: circleci/python:3.10.2

    steps:
      - checkout
      - run:
          command: |
            sudo pip install virtualenv
            sudo pip install nox
            nox -f noxfile.py -s unit
  Compatibility Test:
    docker:
      - image: circleci/python:3.10.2

    steps:
      - checkout
      - run:
          command: |
            sudo pip install virtualenv
            sudo pip install nox
            nox -f noxfile.py -s compatibility
  Lint:
    docker:
      - image: circleci/python:3.10.2

    steps:
      - checkout
      - run:
          command: |
            sudo pip install virtualenv
            sudo pip install nox
            nox -f noxfile.py -s lint
  Type Check:
    docker:
      - image: circleci/python:3.10.2

    steps:
      - checkout
      - run:
          command: |
            sudo pip install virtualenv
            sudo pip install nox
            nox -f noxfile.py -s type_check
  Release:
    docker:
      - image: circleci/python:3.10.2

    steps:
      - checkout
      - run:
         command: |
          sudo pip install --upgrade twine
          sudo pip install --upgrade wheel
          sudo pip install --upgrade setuptools
          source twine_upload.sh


workflows:
  version: 2
  test:
    jobs:
      - Lint
      - Unit Test
      - Type Check
      - Compatibility Test
  release:
    jobs:
      - Release:
          filters:
            # Runs for no branches and only for tags like "1.2.3"
            branches:
              ignore: /.*/
            tags:
              only:
                - /^\d+\.\d+\.\d+$/
